version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    command: --init-file /var/lib/mysql-files/init.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - type: bind
        source: ./src/main/resources/sql
        target: /var/lib/mysql-files
    networks:
      - network1
# Names our volume
volumes:
  my-db:
networks:
  network1:

